# Generated by Django 4.0.6 on 2022-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryaba', '0004_indushation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('availability', models.CharField(choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Moloko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('availability', models.CharField(choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('availability', models.CharField(choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tvorog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('availability', models.CharField(choices=[('Есть в наличии', 'Есть в наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=30)),
            ],
        ),
    ]
