# Generated by Django 4.0.6 on 2022-07-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryaba', '0006_tarelki_vilki'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oformlenie',
            new_name='Zakaz',
        ),
    ]
